default: &default
  adapter: postgresql
  encoding: unicode
  user: postgres
  password: postgres

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_updated_development
  user: postgres
  password: postgres


test:
  <<: *default
  database: budget_updated_test
  user: postgres
  password: postgres


production:
  <<: *default
  database: budget_updated_production
  username: blogapp
  password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %>