default: &default
  adapter: postgresql
  encoding: unicode
  user: yourname
  password: yourname

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: budget_updated_development
  user: yourname
  password: yourname


test:
  <<: *default
  database: budget_updated_test
  user: yourname
  password: yourname


production:
  <<: *default
  database: budget_updated_production
  username: blogapp
  password: <%= ENV["BLOGAPP_DATABASE_PASSWORD"] %>